services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${EMAIL}
    restart: always

  lamp_frontend:
    image: ghcr.io/3underdog/lamp_web_v1:${TAG:-latest}
    container_name: lamp_frontend
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=${HOST}
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
    env_file: .env
    restart: always
    

  # backend:
  #   build: ../nangmanski_backend_spring
  #   container_name: backend
  #   expose:
  #     - 7979
  #   environment:
  #     - VIRTUAL_HOST=api.${HOST}

volumes:
  conf:
  vhost:
  html:
  certs:
  acme: